# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14f9dca105653c2819aa79c6392ccce1a7c9ff68bd6fc5d8c5c33603246f48e81e6885989e1ada394448135e0e923d257b0d987456ba518e61133cd8dca6116d

test:
  secret_key_base: 4fd95deb50684e36b01f42483060b5a1da96394e57efd4a50abbc11c555a8d927a9689a74035c8ae7230c37e3fa0e6d63f69ee8d7a32bee0366f9eb36bb43c4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
